# Generated by Django 5.2.8 on 2025-11-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_person_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del curso', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del curso')),
                ('codigo', models.CharField(help_text='Código del curso', max_length=20, unique=True)),
                ('aula', models.CharField(help_text='Aula asignada', max_length=20)),
                ('sesion', models.CharField(blank=True, help_text='Sesión o turno', max_length=50)),
                ('profesor', models.CharField(help_text='Nombre del profesor', max_length=100)),
                ('horario', models.CharField(help_text='Horario del curso', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nombre'],
            },
        ),
    ]
