# Generated by Django 5.2.8 on 2025-11-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_course_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código del curso', max_length=20, null=True, unique=True),
        ),
    ]
