# Generated by Django 5.2.8 on 2025-11-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_course_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='aula',
            field=models.CharField(choices=[('A-101', 'Aula A-101'), ('A-102', 'Aula A-102'), ('A-103', 'Aula A-103'), ('B-201', 'Aula B-201'), ('B-202', 'Aula B-202'), ('B-203', 'Aula B-203'), ('LAB-1', 'Laboratorio 1'), ('LAB-2', 'Laboratorio 2'), ('LAB-3', 'Laboratorio 3'), ('AULA-MAGNA', 'Aula Magna'), ('BIBLIOTECA', 'Biblioteca'), ('VIRTUAL', 'Aula Virtual')], help_text='Aula asignada', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='horario',
            field=models.CharField(choices=[('08:00-10:00', '08:00 - 10:00 AM'), ('10:00-12:00', '10:00 - 12:00 AM'), ('14:00-16:00', '14:00 - 16:00 PM'), ('16:00-18:00', '16:00 - 18:00 PM'), ('18:00-20:00', '18:00 - 20:00 PM'), ('20:00-22:00', '20:00 - 22:00 PM')], help_text='Horario del curso', max_length=100),
        ),
    ]
