# Generated by Django 5.2.8 on 2025-11-09 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_course_aula_alter_course_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='telefono',
        ),
    ]
